

import localFont from "next/font/local";
import React from "react";
import "./globals.css";
import Sidebar from './Sidebar';



export const metadata = {
  title: "NextVendas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="pt-br">
      <body className="bg-blue-950 text-white">
        <div className="flex h-screen p-4 font-whitney font-semibold">
          <Sidebar/>
          {children}
        </div>
      </body>
    </html>
  );
}
